=== dhrxogus03/PomitDEV/resources/resources/param/DELPPWApplications/xsd/EGraphViewReferenceAttribute.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="DS_DELPPWConfiguration" xmlns:tns="DS_DELPPWConfiguration"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="Config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Preferences">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Primary">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Attribute">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="dicoType" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Secondary">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Attribute">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="dicoType" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Image">
                <xs:complexType>
                  <xs:attribute name="value" type="xs:boolean" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="version" type="xs:string" fixed="2.0" use="required" />
      <xs:attribute name="Title" type="xs:string" use="required"/>
      <xs:attribute name="Description" type="xs:string" use="required"/>
      </xs:complexType>
  </xs:element>
</xs:schema>

=== dhrxogus03/PomitDEV/3dspace/webapps/DELMGAApp/assets/xml/EGraphViewReferenceAttribute.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config version="2.0" xmlns="DS_DELPPWConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELPPWConfiguration ../xsd/EGraphViewReferenceAttribute.xsd" Title="GraphView reference attributes preferences" Description="Sample configuration file delivered by DS.">
    <Preferences>
            <Primary>
                <Attribute name="V_Name" dicoType="PLMEntity"/>
            </Primary>
            <Secondary>
                <Attribute name="type"/>
                <Attribute name="revision"/>
                <!--<Attribute name="CGJMyAttribute1" dicoType="CGJMyDeploymentExtension"/> -->
            </Secondary>
            <Image value="true"/>
    </Preferences>
</Config>
