=== dhrxogus03/PomitDEV/resources/resources/param/DELPPWApplications/xsd/ExportCSVPreferences.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="DS_DELPPWConfiguration" xmlns:tns="DS_DELPPWConfiguration"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="Config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Preferences">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ExportCSV">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Type">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="Attribute">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string" use="required" />
                              <xs:attribute name="dicoType" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="showOptionPanel" type="xs:boolean" use="required" />
                  <xs:attribute name="defaultValue" type="xs:boolean" use="required" />
                  <xs:attribute name="exportUnits" type="xs:boolean" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="version" type="xs:string" fixed="2.0" use="required" />
      <xs:attribute name="Title" type="xs:string" use="required" />
      <xs:attribute name="Description" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dhrxogus03/PomitDEV/3dspace/webapps/DELMGAApp/assets/xml/ExportCSVPreferences.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config version="2.0" xmlns="DS_DELPPWConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELPPWConfiguration ../xsd/ExportCSVPreferences.xsd" Title="ExportCSV preferences" Description="Sample configuration file delivered by DS.">
  <Preferences>
    <ExportCSV showOptionPanel="false" defaultValue="false">
      <Type name="DELLmiGeneralSystemReference">
                <Attribute name="V_Name" dicoType="PLMEntity"/>
                <Attribute name="V_description" dicoType="PLMEntity"/>
            </Type>
            <Type name="DELLmiGeneralOperationReference">
                <Attribute name="V_Name" dicoType="PLMEntity"/>
                <Attribute name="V_description" dicoType="PLMEntity"/>
            </Type>
    </ExportCSV>
  </Preferences>
</Config>
